services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    command:
      [
        "dotnet",
        "watch",
        "run",
        "--project",
        "RpgDex.WebApi/RpgDex.WebApi.csproj",
        "--urls",
        "http://0.0.0.0:8080",
      ]
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ConnectionStrings__MongoDbConnection=${MONGO_CONNECTION}
      - ConnectionStrings__MongoDbName=${MONGO_DB_NAME}
      - ConnectionStrings__MongoDbCollectionName=${MONGO_COLLECTION_NAME}
      - ConnectionStrings__Redis=redis:6379
      - JWT__Key=${JWT_KEY}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE}
      - Jwt__TokenValidityInMinutes=30
      - Jwt__RefreshTokenValidityInMinutes=60
      - Google__ClientId=${GOOGLE_CLIENTID}
      - Discord__ClientId=${DISCORD_CLIENTID}
      - Discord__ClientSecret=${DISCORD_CLIENTSECRET}
      - EmailSettings__ResendApiKey=${RESEND_API_KEY}
      - EmailSettings__SmtpServer=${EMAIL_SMTP_SERVER}
      - EmailSettings__SmtpPort=${EMAIL_SMTP_PORT}
      - EmailSettings__Username=${EMAIL_SMTP_USERNAME}
      - EmailSettings__Password=${EMAIL_SMTP_PASSWORD}
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  mongo-data:
  redis-data:
