name: .NET Core Build e Check

on:
  push:
    branches: [ "main" ] # Roda sempre que você envia algo para a main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: API/RpgDex

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0 # Ou a versão que você está usando

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      env:
        # Aqui o GitHub injeta o seu Secret durante o processo de build/teste
        ConnectionStrings__MongoDbConnection: ${{ secrets.MONGODB_CONNECTION_STRING }}
        Jwt__Key: ${{  secrets.JWT_KEY  }}
  build-angular:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: UI/RpgDexUI
  
      steps:
      - uses: actions/checkout@v4
  
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Ajuste para a versão do Node usada no seu projeto
          cache: 'npm'
          cache-dependency-path: UI/RpgDexUI/package-lock.json
  
      - name: Install dependencies
        run: npm ci
  
      - name: Lint (Opcional)
        run: npm run lint --if-present
  
      - name: Build Angular
        run: npx ng build
